services:
  - type: web
    name: spendsense-app-v2-backend
    plan: free
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: spendsense-app-v2-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: spendsense-app-v2-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: spendsense-app-v2-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: spendsense-app-v2-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: spendsense-app-v2-db
          property: port
  
  - type: web
    name: spendsense-app-v2-frontend
    plan: free
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: spendsense-app-v2-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: spendsense-app-v2-db
    plan: free
    databaseName: expense_tracker
    user: expense_user
